name: Update semver tags

on:
  release:
    types: [published]

jobs:
  update-semver:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Update major and minor tags
        uses: ./
        with:
          mode: prefix
